import type { Equipment } from './types';

// Dados realistas provisórios — usados como fallback quando a API/banco ainda
// não está disponível (mitigação de risco prevista no plano de ação)
export const SAMPLE_EQUIPMENTS: Equipment[] = [
  {
    _id: 'demo-1',
    title: 'Semirreboque Randon 2024 Sider',
    slug: 'semirreboque-randon-2024-sider',
    brand: 'Randon',
    sku: 'SP-SR-2024-001',
    category: 'sider',
    year: 2024,
    axles: 3,
    priceBRL: 185000,
    capacityM3: 40,
    description:
      'Sider Randon 2024 com suspensão pneumática, ideal para cargas paletizadas e operação em rotas de longa distância.',
    images: [{ url: '/placeholder-trailer.svg', alt: 'Semirreboque Randon Sider' }],
    specs: [
      { label: 'Suspensão', value: 'Pneumática' },
      { label: 'Pneus', value: '295/80 R22.5' },
      { label: 'Freios', value: 'ABS' },
    ],
    status: 'publicado',
    availability: 'disponivel',
    featured: true,
  },
  {
    _id: 'demo-2',
    title: 'Semirreboque Librelato 2023 Graneleiro 4 Eixos',
    slug: 'semirreboque-librelato-2023-graneleiro',
    brand: 'Librelato',
    sku: 'SP-LB-2023-002',
    category: 'graneleiro',
    year: 2023,
    axles: 4,
    priceBRL: 185000,
    description:
      'Graneleiro Librelato 4 eixos, preparado para grãos e cargas secas com alta capacidade volumétrica.',
    images: [{ url: '/placeholder-trailer.svg', alt: 'Semirreboque Librelato Graneleiro' }],
    specs: [{ label: 'Suspensão', value: 'Mecânica' }],
    status: 'publicado',
    availability: 'disponivel',
    featured: true,
  },
  {
    _id: 'demo-3',
    title: 'Semirreboque Facchini 2024 Frigorífico Thermo King',
    slug: 'semirreboque-facchini-2024-frigorifico',
    brand: 'Facchini',
    sku: 'SP-FC-2024-003',
    category: 'frigorifico',
    year: 2024,
    axles: 3,
    priceBRL: 185000,
    lengthM: 14.6,
    description:
      'Frigorífico Facchini com aparelho Thermo King, controle de temperatura para cargas refrigeradas e congeladas.',
    images: [{ url: '/placeholder-trailer.svg', alt: 'Semirreboque Facchini Frigorífico' }],
    specs: [{ label: 'Aparelho', value: 'Thermo King' }],
    status: 'publicado',
    availability: 'disponivel',
    featured: true,
  },
  {
    _id: 'demo-4',
    title: 'Semirreboque Randon 2023 Prancha Carga Rebaixada',
    slug: 'semirreboque-randon-2023-prancha',
    brand: 'Randon',
    sku: 'SP-PR-2023-004',
    category: 'prancha',
    year: 2023,
    axles: 4,
    priceBRL: 118000,
    lengthM: 15,
    description:
      'Prancha rebaixada Randon para transporte de máquinas e equipamentos pesados, com rampas traseiras.',
    images: [{ url: '/placeholder-trailer.svg', alt: 'Semirreboque Randon Prancha' }],
    specs: [{ label: 'Rampas', value: 'Traseiras hidráulicas' }],
    status: 'publicado',
    availability: 'disponivel',
    featured: true,
  },
];
